name: Linting and Unittesting

on:
  push:
    paths:
      - '**.py'
      - 'pyproject.toml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: pip install -e .[test]
        
      - name: Run pre-commit
        run: pre-commit run --all-files

  unittest:
    name: Unittest
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ always() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: pip install -e .[test]
        
      - name: Run pytest
        run: pytest
